FROM nginx:1.25

# Tools Debug
RUN apt-get update
RUN apt-get -y install net-tools \
                       curl \
                       netcat-openbsd \
                       wget \
                       vim \
                       telnet \
                       procps \	
                       tzdata \
                       dnsutils 

# Defina o diretório de trabalho
WORKDIR /etc/nginx/

# Config Timezone						
COPY devops/timezone/Sao_Paulo /etc/localtime
RUN echo "America/Sao_Paulo" > /etc/timezone

# Config Nginx
COPY devops/nginx/nginx.conf /etc/nginx/nginx.conf

# Config VirtualHost
COPY devops/nginx/vhost/*.conf /etc/nginx/vhost/

# Config Static
COPY ../app/static/ /usr/share/nginx/static

