apiVersion: v1
kind: Service
metadata:
  labels:
    app: urbanfood-be-pod
  name: urbanfood-be-loadbalancer-svc
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: urbanfood-be-pod
  type: LoadBalancer