apiVersion: v1
kind: Pod
metadata:
  name: urbanfood-be-pod
  labels:
        app: urbanfood-be-pod
spec:
  containers:
    - name: urbanfood-be
      image: 477719197904.dkr.ecr.us-east-1.amazonaws.com/fiap/urbanfood:1.0.0
      ports:
        - containerPort: 8000
      env:
        - name: MYSQL_HOST
          value: 'mysql-loadbalancer-svc'
        - name: MYSQL_PORT
          value: '3306'  