# Generated by Django 5.1 on 2025-03-17 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cliente", "0001_initial"),
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                ("data", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "fk_cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cliente.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedidos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Recebido", "Recebido"),
                            ("Em_preparação", "Em_preparação"),
                            ("Pronto", "Pronto"),
                            ("Finalizado", "Finalizado"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "fk_checkout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pedidos.checkout",
                    ),
                ),
                (
                    "fk_produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produtos.produtos",
                    ),
                ),
            ],
        ),
    ]
