# Generated by Django 5.1 on 2025-03-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("cpf", models.CharField(blank=True, max_length=100, null=True)),
                ("data_aniversario", models.DateField(blank=True, null=True)),
                ("profissao", models.CharField(blank=True, max_length=100, null=True)),
                ("telefone", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=255)),
            ],
        ),
    ]
