apiVersion: apps/v1
kind: Deployment
metadata:
  name: urbanfood
  namespace: urban-food
  labels:
    app: urbanfood
spec:
  replicas: 2
  selector:
    matchLabels:
      app: urbanfood
  template:
    metadata:
      labels:
        app: urbanfood
    spec:
      containers:
        - name: urbanfood
          image: 477719197904.dkr.ecr.us-east-1.amazonaws.com/fiap/urbanfood:1.0.0
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: urbanfood-config
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 30
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 300Mi                     