apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-urbanfood
  name: app-urbanfood
  namespace: urbanfood
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: app-urbanfood
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate      
  template:
    metadata:
      labels:
        app: app-urbanfood
    spec:
      containers:
        - name: app-urbanfood
          image: 857378965163.dkr.ecr.us-east-1.amazonaws.com/urbanfood-app/app:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: app-configmap
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 3
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 5
            initialDelaySeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 200m
              memory: 768Mi
      dnsPolicy: ClusterFirst
      securityContext: {}          
