apiVersion: v1
kind: Service
metadata:
  name: service-app-urbanfood
  namespace: urbanfood
  labels:
    app: app-urbanfood 
spec:
  ports:
  - name: service-app-http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: app-urbanfood
  type: LoadBalancer