# Generated by Django 5.1 on 2025-03-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produtos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Lanche", "Lanche"),
                            ("Acompanhamento", "Acompanhamento"),
                            ("Bebida", "Bebida"),
                            ("Sobremesa", "Sobremesa"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("preco_unitario", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
