apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysqldb
  name: mysqldb
  namespace: urban-food
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysqldb
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysqldb
    spec:   
      containers:
        - name: mysqldb
          image: 477719197904.dkr.ecr.us-east-1.amazonaws.com/fiap/mysqldb:8.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306     
          env:
           - name: MYSQL_ROOT_PASSWORD
             valueFrom:
              secretKeyRef: 
                name: mysqldb-secret
                key: MYSQL_ROOT_PASSWORD
           - name: MYSQL_USER
             valueFrom:
              secretKeyRef: 
                name: mysqldb-secret
                key: MYSQL_USER   
           - name: MYSQL_PASSWORD
             valueFrom:
              secretKeyRef: 
                name: mysqldb-secret
                key: MYSQL_PASSWORD
           - name: MYSQL_DATABASE
             valueFrom:
              secretKeyRef: 
                name: mysqldb-secret
                key: MYSQL_DATABASE
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
            - mountPath: /tmp
              name: tmp                            
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysqldb-pvc
        - name: tmp
          emptyDir: {}
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true                                    
                                  