apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldb-pvc
  namespace: urban-food
  labels:
    run: mysqldb
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

