apiVersion: v1
kind: Secret
metadata:
  name: mysqldb-secret
  namespace: urban-food
type: Opaque
stringData:
  MYSQL_USER: "urban_food"
  MYSQL_DATABASE: "urban_food"
  MYSQL_PASSWORD: "@UrbanF00D@"
  MYSQL_ROOT_PASSWORD: "@UrbanF00D@"
immutable: true    