apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mysqldb-hpa
  namespace: urban-food
spec:
  minReplicas: 2
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mysqldb
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80  