---
name: Build and push app urban food Image to AWS ECR
on:
  push:
    branches: [ "main" ]

env:
  PYENV: PROD
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY_APP: ${{ secrets.ECR_REPOSITORY_APP }}

permissions:
    id-token: write
    contents: read
    packages: write
    attestations: write

jobs:
  build_app:
    name: Build and Push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Config AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::857378965163:role/github-actions

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - run: echo "$ECR_REGISTRY/$ECR_REPOSITORY_APP:$IMAGE_TAG"
      - run: echo "$ECR_REGISTRY/$ECR_REPOSITORY_APP:$IMAGE_TAG" > imageName.txt
      - uses: actions/upload-artifact@v4
        with:
          name: imageName
          path: imageName.txt

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: urbanfood-app/app
          IMAGE_TAG: latest
        run: |
          docker build --no-cache --progress=plain -f devops/Dockerfile-App --build-arg PYENV="$PYENV" --build-arg APP_FOLDER=app/ -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
