---
name: Build and push app urbanfood Image to AWS ECR
on:
  push:
    branches: [ "main" ]

env:
  PYENV: ${{ vars.ENV }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ vars.EKS_CLUSTER_NAME }}

permissions:
    id-token: write
    contents: read
    packages: write
    attestations: write

jobs:
  build_app:
    name: Build and Push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: marcofranssen/setup-kubectl@v0.3.0
        id: kubectl
      - run: echo ${{ steps.kubectl.output.kubectl-version }}        

      - name: Config AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::857378965163:role/github-actions

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./devops/git_update.sh -v patch

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          IMAGE_RELEASE: ${{ steps.increment-git-tag.outputs.git-tag }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: urbanfood-app/app
          IMAGE_TAG: latest
        run: |
          docker build --no-cache --progress=plain -f devops/Dockerfile-App --build-arg PYENV="$PYENV" --build-arg APP_FOLDER=app/ -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_RELEASE .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_RELEASE $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG          
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_RELEASE
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - run: echo "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_RELEASE" > imageName.txt
      - uses: actions/upload-artifact@v4
        with:
          name: imageName
          path: imageName.txt          

      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Deploy to APP EKS
        run: |
          kubectl apply -f k8s/namespace.yml
          kubectl apply -f k8s/app/urbanfood-configmap.yaml
          kubectl apply -f k8s/app/urbanfood-hpa.yaml
          kubectl apply -f k8s/app/urbanfood-service.yaml
          kubectl apply -f k8s/app/urbanfood-deployment.yaml